PROJECT_LABEL="CRM Domain"

dev_MANIFEST="manifest_dev.yml"
dev_STAGE="CRM_DEV.PUBLIC.CRM_DCM_STAGE"
dev_PROJECT="CRM_DEV.PUBLIC.CRM_DCM_DEV"
dev_CONFIG="dev"

prod_MANIFEST="manifest_prod.yml"
prod_STAGE="CRM_PRD.PUBLIC.CRM_DCM_STAGE"
prod_PROJECT="CRM_PRD.PUBLIC.CRM_DCM_PRD"
prod_CONFIG="prod"
